name: aesd
description: "New aesd application based on Buzz templates"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0-0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_svg: ^2.0.6
  intl: any
  file_picker: ^10.2.0
  dotted_border: ^2.0.0+3
  boardview: ^1.0.0
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^5.1.1
  weekly_date_picker: ^1.3.0
  google_fonts: ^6.2.1
  http: ^1.0.0
  url_launcher: ^6.1.1
  otp_text_field: ^1.1.3
  flutter_locales: ^3.0.1
  lottie: ^3.3.1
  provider: ^6.0.5
  dropdown_button2: ^2.1.4
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  dio: ^5.8.0+1
  image_picker: ^1.1.2
  loading_overlay: ^0.4.3
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  device_info_plus: ^9.0.0
  fast_cached_network_image: ^1.3.3+5
  shimmer: ^3.0.0
  photo_view: ^0.15.0
  path_provider: ^2.1.5
  record: ^6.1.1
  audioplayers: ^6.5.0
  video_player: ^2.0.0
  chewie: ^1.8.3
  date_field: ^6.0.0
  accordion: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

# Configuration de l'icÃ´ne de l'application
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/launcher_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/launcher_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/illustrations/
    - assets/locales/ar.json
    - assets/locales/en.json

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Medium.otf